#release configuration
#Tue Sep 29 11:12:07 CDT 2026
projectVersionPolicyId=default
project.rel.net.imagej\:imagej-legacy=3.0.0
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
pinExternals=false
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
project.scm.net.imagej\:imagej-legacy.tag=HEAD
exec.activateProfiles=deploy-to-scijava
pushChanges=false
remoteTagging=true
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
releaseStrategyId=default
project.scm.net.imagej\:imagej-legacy.url=https\://github.com/imagej/imagej-legacy
completedPhase=end-release
scm.url=scm\:git\:https\://github.com/imagej/imagej-legacy
scm.developmentCommitComment=@{prefix} prepare for next development iteration
exec.additionalArguments=-Dgpg.skip\=true 
scm.tagNameFormat=@{project.artifactId}-@{project.version}
project.scm.net.imagej\:imagej-legacy.connection=scm\:git\:https\://github.com/imagej/imagej-legacy
scm.tag=imagej-legacy-3.0.0
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
project.scm.net.imagej\:imagej-legacy.developerConnection=scm\:git\:git@github.com\:imagej/imagej-legacy
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
exec.pomFileName=pom.xml
project.dev.net.imagej\:imagej-legacy=3.0.1-SNAPSHOT
